### ISSUE TITLE
ClusterAuthorizationStatusRestricted

### ISSUE THREAD

**Issue by confile** [clusterinc/ClusterPrePermissions#21]
When is the ``ClusterAuthorizationStatusRestricted``status of ``ClusterAuthorizationStatus`` being used?

**Comment by rsattar** [comment]
It's used only within the class methods that check the authorization status (`+ (ClusterAuthorizationStatus) [type]PermissionAuthorizationStatus`). When it is returned it means that the user (or their parent/guardian) has restricted access to that resource. They can do this in Settings.app > General > Restrictions.

It's rare to come across this scenario, but it is treated separately than a "Denied Permission" by iOS and so ClusterPrePermissions also honors that distinction. Hope that helps?

**Comment by confile** [comment]
What should I do in this Case?

**Comment by rsattar** [comment]
In general you don't have access to the resource, just as if the user manually denied permission. However, the messaging in your app should usually be different. 

Rather than saying, for example, `We can't show you pictures because you denied access to them.`, you might want to show something like `We can't show you pictures because there are restrictions preventing some apps from accessing your photo library. To change this, go to Settings.app > General > Restrictions > Photos`, or something to that effect.

**Comment by confile** [comment]
Are these restrictions available also for location permission?

**Comment by rsattar** [comment]
Almost every one of the permissions can be restricted, yes. Please check your iPhone's Settings.app > General > Restrictions, and you'll see everything that can be locked down.

**Comment by confile** [comment]
Thanks for help
